/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cEtchesSol from "./CEtches.sol";
export type { cEtchesSol };
import type * as cNodeHandlerSol from "./CNodeHandler.sol";
export type { cNodeHandlerSol };
import type * as cOrganisationSol from "./COrganisation.sol";
export type { cOrganisationSol };
import type * as cTeamsSol from "./CTeams.sol";
export type { cTeamsSol };
import type * as forks from "./forks";
export type { forks };
export type { IEtches } from "./IEtches";
export type { IOrganisation } from "./IOrganisation";
export type { ITeams } from "./ITeams";
