/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SignatureVerifier,
  SignatureVerifierInterface,
} from "../../../contracts/CSignatureVerifier.sol/SignatureVerifier";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "encodedMessage",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "messageHash",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "signer",
            type: "address",
          },
        ],
        internalType: "struct SignatureVerifier.Signature",
        name: "_signature",
        type: "tuple",
      },
    ],
    name: "checkSignature",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "blockNumber",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "nodeAddress",
            type: "address",
          },
        ],
        internalType: "struct SignatureVerifier.EncodedMessage",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SignatureVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): SignatureVerifierInterface {
    return new Interface(_abi) as SignatureVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SignatureVerifier {
    return new Contract(address, _abi, runner) as unknown as SignatureVerifier;
  }
}
