import React, { useRef, useState } from "react";
import { DialogDescription } from "./dialog";
import { Button } from "./button";
import { Icons } from "./icons";
import { OtpInputs } from "./otp";
import { form } from "../pages/profile";

export default function ScanQrCode({
  verifyCode,
  setVerifyCode,
  setForm,
}: {
  verifyCode: string;
  setVerifyCode: React.Dispatch<string>;
  setForm: React.Dispatch<form>;
}) {
  const [otp, setOtp] = useState(Array(6).fill(""));

  const verify = (e: any) => {
    e.preventDefault();
    const emptyInput = otp.filter((item: string) => item != "5");

    if (emptyInput.length < 1) {
      setVerifyCode("success");
    } else {
      setVerifyCode("error");
    }
  };

  const props = { verifyCode, otp, setOtp };

  return (
    <main className="mt-7">
      <div className="mb-5 px-8 text-center font-body text-sm font-medium text-muted-foreground">
        You will need Google Authenticator to complete this process.
      </div>
      <section>
        <div className="mt-5 text-center font-body text-xs font-bold text-foreground">Scan QR Code into your app</div>
        <Icons.qrCode className="mx-auto" />
      </section>
      <section className="mb-5 mt-8 h-[1px] w-full bg-muted" />
      <form onSubmit={verify} className="px-8">
        <div className="mb-4 px-8 text-center font-body text-xs font-bold text-foreground">
          Enter 6 digit authentication code generated by your app
        </div>
        <OtpInputs {...props} />
        <footer className="mt-10 flex items-center justify-end gap-5">
          <div onClick={() => setForm({ status: false })} className="cursor-pointer text-sm font-semibold hover:text-foreground">
            Cancel
          </div>
          <Button type="submit">Verify</Button>
        </footer>
      </form>
    </main>
  );
}
