/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEtches {
  export type SCommentsStruct = {
    commentIpfsCid: string;
    timestamp: BigNumberish;
  };

  export type SCommentsStructOutput = [
    commentIpfsCid: string,
    timestamp: bigint
  ] & { commentIpfsCid: string; timestamp: bigint };
}

export declare namespace SignatureVerifier {
  export type EncodedMessageStruct = {
    blockNumber: BigNumberish;
    nodeAddress: AddressLike;
  };

  export type EncodedMessageStructOutput = [
    blockNumber: bigint,
    nodeAddress: string
  ] & { blockNumber: bigint; nodeAddress: string };

  export type SignatureStruct = {
    encodedMessage: BytesLike;
    messageHash: BytesLike;
    signature: BytesLike;
    signer: AddressLike;
  };

  export type SignatureStructOutput = [
    encodedMessage: string,
    messageHash: string,
    signature: string,
    signer: string
  ] & {
    encodedMessage: string;
    messageHash: string;
    signature: string;
    signer: string;
  };
}

export interface $EtchesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "$__unsafe_increaseBalance"
      | "$_afterTokenTransfer"
      | "$_approve"
      | "$_baseURI"
      | "$_beforeTokenTransfer"
      | "$_burn"
      | "$_checkOwner"
      | "$_checkPermssion"
      | "$_exists"
      | "$_isApprovedOrOwner"
      | "$_mint"
      | "$_msgData"
      | "$_msgSender"
      | "$_ownerOf"
      | "$_owners"
      | "$_requireMinted"
      | "$_safeMint(address,uint256,bytes)"
      | "$_safeMint(address,uint256)"
      | "$_safeTransfer(address,address,uint256,bytes)"
      | "$_safeTransfer(address,address,uint256)"
      | "$_setApprovalForAll"
      | "$_transfer"
      | "$_transferOwnership"
      | "$checkMessageValidity"
      | "$getEthSignedMessageHash"
      | "$getMessageHash"
      | "__hh_exposed_bytecode_marker"
      | "_nodes"
      | "addNode"
      | "approve"
      | "balanceOf"
      | "checkSignature"
      | "commentOnEtch"
      | "commentsOf"
      | "delegateCallsToSelf"
      | "getApproved"
      | "getParent"
      | "getTotalSupply"
      | "hasReadPermission"
      | "hasWritePermission"
      | "indexOfTeamPermissionsOf"
      | "individualPermissionsOf"
      | "isApprovedForAll"
      | "isNode"
      | "metadataOf"
      | "name"
      | "owner"
      | "ownerOf"
      | "renounceOwnership"
      | "safeMint"
      | "safeMintForTeam"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setIndividualPermissions"
      | "setMetadata"
      | "setTeamPermissions"
      | "supportsInterface"
      | "symbol"
      | "teamOf"
      | "teamPermissionsOf"
      | "teams"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "transferToTeam"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "CommentAdded"
      | "EtchCreated"
      | "EtchMetadataUpdated"
      | "EtchTransferedToTeam"
      | "InvididualPermissionsUpdated"
      | "OwnershipTransferred"
      | "TeamPermissionsUpdated"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "$__unsafe_increaseBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_afterTokenTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "$_baseURI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "$_beforeTokenTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_burn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_checkOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "$_checkPermssion",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_exists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_isApprovedOrOwner",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "$_msgData", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "$_msgSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "$_ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_requireMinted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_safeMint(address,uint256,bytes)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "$_safeMint(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_safeTransfer(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "$_safeTransfer(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_setApprovalForAll",
    values: [AddressLike, AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "$_transfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "$_transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "$checkMessageValidity",
    values: [SignatureVerifier.EncodedMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "$getEthSignedMessageHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "$getMessageHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "__hh_exposed_bytecode_marker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_nodes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "addNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [SignatureVerifier.SignatureStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "commentOnEtch",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "commentsOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateCallsToSelf",
    values: [SignatureVerifier.SignatureStruct, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getParent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasReadPermission",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWritePermission",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "indexOfTeamPermissionsOf",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "individualPermissionsOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isNode", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "metadataOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeMint",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeMintForTeam",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setIndividualPermissions",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetadata",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTeamPermissions",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "teamOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "teamPermissionsOf",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "teams", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToTeam",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "$__unsafe_increaseBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_afterTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "$_approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "$_baseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "$_beforeTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "$_burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "$_checkOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_checkPermssion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "$_exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "$_isApprovedOrOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "$_mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "$_msgData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "$_msgSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "$_ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "$_owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "$_requireMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_safeMint(address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_safeMint(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_safeTransfer(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_safeTransfer(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$_setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "$_transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "$_transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$checkMessageValidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$getEthSignedMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "$getMessageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__hh_exposed_bytecode_marker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_nodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commentOnEtch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commentsOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegateCallsToSelf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getParent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReadPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasWritePermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "indexOfTeamPermissionsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "individualPermissionsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metadataOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeMintForTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIndividualPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTeamPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "teamOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "teamPermissionsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teams", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToTeam",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommentAddedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    commentId: BigNumberish,
    comment: IEtches.SCommentsStruct
  ];
  export type OutputTuple = [
    tokenId: bigint,
    commentId: bigint,
    comment: IEtches.SCommentsStructOutput
  ];
  export interface OutputObject {
    tokenId: bigint;
    commentId: bigint;
    comment: IEtches.SCommentsStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EtchCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    to: AddressLike,
    ipfsCid: string,
    documentName: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    to: string,
    ipfsCid: string,
    documentName: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    to: string;
    ipfsCid: string;
    documentName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EtchMetadataUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    ipfsCid: string,
    documentName: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    ipfsCid: string,
    documentName: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    ipfsCid: string;
    documentName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EtchTransferedToTeamEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    from: AddressLike,
    to: BigNumberish
  ];
  export type OutputTuple = [tokenId: bigint, from: string, to: bigint];
  export interface OutputObject {
    tokenId: bigint;
    from: string;
    to: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvididualPermissionsUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    account: AddressLike,
    newPermission: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    account: string,
    newPermission: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    account: string;
    newPermission: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeamPermissionsUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    teamId: BigNumberish,
    newPermission: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    teamId: bigint,
    newPermission: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    teamId: bigint;
    newPermission: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface $Etches extends BaseContract {
  connect(runner?: ContractRunner | null): $Etches;
  waitForDeployment(): Promise<this>;

  interface: $EtchesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  $__unsafe_increaseBalance: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  $_afterTokenTransfer: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      firstTokenId: BigNumberish,
      batchSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  $_approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  $_baseURI: TypedContractMethod<[], [string], "view">;

  $_beforeTokenTransfer: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      firstTokenId: BigNumberish,
      batchSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  $_burn: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  $_checkOwner: TypedContractMethod<[], [void], "view">;

  $_checkPermssion: TypedContractMethod<
    [account: AddressLike, tokenId: BigNumberish, permission: BigNumberish],
    [boolean],
    "view"
  >;

  $_exists: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  $_isApprovedOrOwner: TypedContractMethod<
    [spender: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  $_mint: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  $_msgData: TypedContractMethod<[], [string], "view">;

  $_msgSender: TypedContractMethod<[], [string], "view">;

  $_ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  $_owners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  $_requireMinted: TypedContractMethod<[tokenId: BigNumberish], [void], "view">;

  "$_safeMint(address,uint256,bytes)": TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  "$_safeMint(address,uint256)": TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "$_safeTransfer(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "$_safeTransfer(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  $_setApprovalForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  $_transfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  $_transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  $checkMessageValidity: TypedContractMethod<
    [_encodedMessage: SignatureVerifier.EncodedMessageStruct],
    [boolean],
    "view"
  >;

  $getEthSignedMessageHash: TypedContractMethod<
    [_messageHash: BytesLike],
    [string],
    "view"
  >;

  $getMessageHash: TypedContractMethod<[_data: BytesLike], [string], "view">;

  __hh_exposed_bytecode_marker: TypedContractMethod<[], [string], "view">;

  _nodes: TypedContractMethod<[node: AddressLike], [boolean], "view">;

  addNode: TypedContractMethod<[node: AddressLike], [void], "nonpayable">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  checkSignature: TypedContractMethod<
    [_signature: SignatureVerifier.SignatureStruct],
    [SignatureVerifier.EncodedMessageStructOutput],
    "view"
  >;

  commentOnEtch: TypedContractMethod<
    [tokenId: BigNumberish, commentIpfsCid: string],
    [void],
    "nonpayable"
  >;

  commentsOf: TypedContractMethod<
    [etch: BigNumberish],
    [[string, bigint] & { commentIpfsCid: string; timestamp: bigint }],
    "view"
  >;

  delegateCallsToSelf: TypedContractMethod<
    [signature: SignatureVerifier.SignatureStruct, _calldata: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getParent: TypedContractMethod<[], [string], "view">;

  getTotalSupply: TypedContractMethod<[], [bigint], "view">;

  hasReadPermission: TypedContractMethod<
    [account: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  hasWritePermission: TypedContractMethod<
    [account: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  indexOfTeamPermissionsOf: TypedContractMethod<
    [etch: BigNumberish, team: BigNumberish],
    [bigint],
    "view"
  >;

  individualPermissionsOf: TypedContractMethod<
    [etch: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  isNode: TypedContractMethod<[node: AddressLike], [boolean], "view">;

  metadataOf: TypedContractMethod<
    [etch: BigNumberish],
    [
      [string, string, string, bigint, bigint] & {
        creator: string;
        documentName: string;
        ipfsCid: string;
        commentsCount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  safeMint: TypedContractMethod<
    [to: AddressLike, documentName: string, ipfsCid: string],
    [bigint],
    "nonpayable"
  >;

  safeMintForTeam: TypedContractMethod<
    [teamId: BigNumberish, documentName: string, ipfsCid: string],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setIndividualPermissions: TypedContractMethod<
    [tokenId: BigNumberish, account: AddressLike, permission: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMetadata: TypedContractMethod<
    [tokenId: BigNumberish, documentName: string, ipfsCid: string],
    [void],
    "nonpayable"
  >;

  setTeamPermissions: TypedContractMethod<
    [tokenId: BigNumberish, teamId: BigNumberish, permission: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  teamOf: TypedContractMethod<[etch: BigNumberish], [bigint], "view">;

  teamPermissionsOf: TypedContractMethod<
    [etch: BigNumberish, arg1: BigNumberish],
    [[bigint, bigint] & { teamId: bigint; permission: bigint }],
    "view"
  >;

  teams: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferToTeam: TypedContractMethod<
    [tokenId: BigNumberish, teamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "$__unsafe_increaseBalance"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_afterTokenTransfer"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      firstTokenId: BigNumberish,
      batchSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_baseURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "$_beforeTokenTransfer"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      firstTokenId: BigNumberish,
      batchSize: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_burn"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "$_checkOwner"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "$_checkPermssion"
  ): TypedContractMethod<
    [account: AddressLike, tokenId: BigNumberish, permission: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "$_exists"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "$_isApprovedOrOwner"
  ): TypedContractMethod<
    [spender: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "$_mint"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_msgData"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "$_msgSender"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "$_ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "$_owners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "$_requireMinted"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "view">;
  getFunction(
    nameOrSignature: "$_safeMint(address,uint256,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_safeMint(address,uint256)"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_safeTransfer(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_safeTransfer(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_setApprovalForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_transfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "$_transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "$checkMessageValidity"
  ): TypedContractMethod<
    [_encodedMessage: SignatureVerifier.EncodedMessageStruct],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "$getEthSignedMessageHash"
  ): TypedContractMethod<[_messageHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "$getMessageHash"
  ): TypedContractMethod<[_data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "__hh_exposed_bytecode_marker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_nodes"
  ): TypedContractMethod<[node: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "addNode"
  ): TypedContractMethod<[node: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkSignature"
  ): TypedContractMethod<
    [_signature: SignatureVerifier.SignatureStruct],
    [SignatureVerifier.EncodedMessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "commentOnEtch"
  ): TypedContractMethod<
    [tokenId: BigNumberish, commentIpfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commentsOf"
  ): TypedContractMethod<
    [etch: BigNumberish],
    [[string, bigint] & { commentIpfsCid: string; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "delegateCallsToSelf"
  ): TypedContractMethod<
    [signature: SignatureVerifier.SignatureStruct, _calldata: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getParent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasReadPermission"
  ): TypedContractMethod<
    [account: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasWritePermission"
  ): TypedContractMethod<
    [account: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "indexOfTeamPermissionsOf"
  ): TypedContractMethod<
    [etch: BigNumberish, team: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "individualPermissionsOf"
  ): TypedContractMethod<
    [etch: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNode"
  ): TypedContractMethod<[node: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "metadataOf"
  ): TypedContractMethod<
    [etch: BigNumberish],
    [
      [string, string, string, bigint, bigint] & {
        creator: string;
        documentName: string;
        ipfsCid: string;
        commentsCount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeMint"
  ): TypedContractMethod<
    [to: AddressLike, documentName: string, ipfsCid: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeMintForTeam"
  ): TypedContractMethod<
    [teamId: BigNumberish, documentName: string, ipfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIndividualPermissions"
  ): TypedContractMethod<
    [tokenId: BigNumberish, account: AddressLike, permission: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMetadata"
  ): TypedContractMethod<
    [tokenId: BigNumberish, documentName: string, ipfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTeamPermissions"
  ): TypedContractMethod<
    [tokenId: BigNumberish, teamId: BigNumberish, permission: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "teamOf"
  ): TypedContractMethod<[etch: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "teamPermissionsOf"
  ): TypedContractMethod<
    [etch: BigNumberish, arg1: BigNumberish],
    [[bigint, bigint] & { teamId: bigint; permission: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "teams"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferToTeam"
  ): TypedContractMethod<
    [tokenId: BigNumberish, teamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "CommentAdded"
  ): TypedContractEvent<
    CommentAddedEvent.InputTuple,
    CommentAddedEvent.OutputTuple,
    CommentAddedEvent.OutputObject
  >;
  getEvent(
    key: "EtchCreated"
  ): TypedContractEvent<
    EtchCreatedEvent.InputTuple,
    EtchCreatedEvent.OutputTuple,
    EtchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EtchMetadataUpdated"
  ): TypedContractEvent<
    EtchMetadataUpdatedEvent.InputTuple,
    EtchMetadataUpdatedEvent.OutputTuple,
    EtchMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EtchTransferedToTeam"
  ): TypedContractEvent<
    EtchTransferedToTeamEvent.InputTuple,
    EtchTransferedToTeamEvent.OutputTuple,
    EtchTransferedToTeamEvent.OutputObject
  >;
  getEvent(
    key: "InvididualPermissionsUpdated"
  ): TypedContractEvent<
    InvididualPermissionsUpdatedEvent.InputTuple,
    InvididualPermissionsUpdatedEvent.OutputTuple,
    InvididualPermissionsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TeamPermissionsUpdated"
  ): TypedContractEvent<
    TeamPermissionsUpdatedEvent.InputTuple,
    TeamPermissionsUpdatedEvent.OutputTuple,
    TeamPermissionsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "CommentAdded(uint256,uint256,tuple)": TypedContractEvent<
      CommentAddedEvent.InputTuple,
      CommentAddedEvent.OutputTuple,
      CommentAddedEvent.OutputObject
    >;
    CommentAdded: TypedContractEvent<
      CommentAddedEvent.InputTuple,
      CommentAddedEvent.OutputTuple,
      CommentAddedEvent.OutputObject
    >;

    "EtchCreated(uint256,address,string,string)": TypedContractEvent<
      EtchCreatedEvent.InputTuple,
      EtchCreatedEvent.OutputTuple,
      EtchCreatedEvent.OutputObject
    >;
    EtchCreated: TypedContractEvent<
      EtchCreatedEvent.InputTuple,
      EtchCreatedEvent.OutputTuple,
      EtchCreatedEvent.OutputObject
    >;

    "EtchMetadataUpdated(uint256,string,string)": TypedContractEvent<
      EtchMetadataUpdatedEvent.InputTuple,
      EtchMetadataUpdatedEvent.OutputTuple,
      EtchMetadataUpdatedEvent.OutputObject
    >;
    EtchMetadataUpdated: TypedContractEvent<
      EtchMetadataUpdatedEvent.InputTuple,
      EtchMetadataUpdatedEvent.OutputTuple,
      EtchMetadataUpdatedEvent.OutputObject
    >;

    "EtchTransferedToTeam(uint256,address,uint256)": TypedContractEvent<
      EtchTransferedToTeamEvent.InputTuple,
      EtchTransferedToTeamEvent.OutputTuple,
      EtchTransferedToTeamEvent.OutputObject
    >;
    EtchTransferedToTeam: TypedContractEvent<
      EtchTransferedToTeamEvent.InputTuple,
      EtchTransferedToTeamEvent.OutputTuple,
      EtchTransferedToTeamEvent.OutputObject
    >;

    "InvididualPermissionsUpdated(uint256,address,uint8)": TypedContractEvent<
      InvididualPermissionsUpdatedEvent.InputTuple,
      InvididualPermissionsUpdatedEvent.OutputTuple,
      InvididualPermissionsUpdatedEvent.OutputObject
    >;
    InvididualPermissionsUpdated: TypedContractEvent<
      InvididualPermissionsUpdatedEvent.InputTuple,
      InvididualPermissionsUpdatedEvent.OutputTuple,
      InvididualPermissionsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TeamPermissionsUpdated(uint256,uint256,uint8)": TypedContractEvent<
      TeamPermissionsUpdatedEvent.InputTuple,
      TeamPermissionsUpdatedEvent.OutputTuple,
      TeamPermissionsUpdatedEvent.OutputObject
    >;
    TeamPermissionsUpdated: TypedContractEvent<
      TeamPermissionsUpdatedEvent.InputTuple,
      TeamPermissionsUpdatedEvent.OutputTuple,
      TeamPermissionsUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
