export const model_formats = {
  "application/x-3ds": [".3ds"],
  "model/3mf": [".3mf"],
  "model/vnd.in3d.3dml": [".ac"],
  "application/amf": [".amf"],
  "application/x-blender": [".blend"],
  "application/x-bvh": [".bvh"],
  "application/vnd.clonk.c4group": [".c4d"],
  "application/x-cob": [".cob"],
  "application/x-csm": [".csm"],
  "application/xml": [".dae"],
  "image/vnd.dxf": [".dxf"],
  "application/x-houdini-material": [".hmp"],
  "model/gltf+json": [".gltf"],
  "model/gltf-binary": [".glb"],
  "application/x-iso9660-image": [".ifc"],
  "model/vnd.jt": [".jt"],
  "application/x-lwo": [".lwo"],
  "application/x-lws": [".lws"],
  "application/vnd.mynfc": [".m3d"],
  "model/x-milkshape3d": [".md2"],
  "application/x-doom": [".md3"],
  "application/x-md5": [".md5"],
  "application/x-ms3d": [".ms3d"],
  "text/plain": [".nff", ".off"],
  "model/obj": [".obj"],
  "model/vnd.opengex": [".ogex"],
  "application/vnd.onshape": [".onshape"],
  "model/ply": [".ply"],
  "x-world/x-3dmf": [".q3d"],
  "application/x-sgi-rgb": [".sib"],
  "application/step-iso": [".step"],
  "application/vnd.unity": [".unitybundle"],
  "model/x3d+xml": [".x3d"],
  "application/xgl": [".xgl"],
  "model/stl": [".stl"],
};
